experiment:
  attacks:
  - ${attack}

attack: null

# ====

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      partitioner: iid
      +datasets: nfv2/sampled/cicids
      batch_size: 32,512
      +epochs: 300/1x300,300/4x75,300/10x30
      +distribution: 5-5
      +target: untargeted
      +scenario: continuous-100
      seed: 1138,421,1313,5555,6567,327,2187,1977,501,3263827